html/modules/custom/ocha_assessments/component/package-lock.json
html/modules/custom/ocha_assessments/component/package.json
html/modules/custom/ocha_assessments/component/src/index.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-map.html

Map cluster

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/cd-table/cd-table.css
html/themes/custom/common_design_subtheme/components/cd-table/cd-table.html
html/themes/custom/common_design_subtheme/js/cd-responsive-tables.js
html/themes/custom/common_design_subtheme/templates/views/views-view-table.html.twig

Add cd-table CSS and js and override Views table template to add as library and add classes

AR-173 cd-table component

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-styles.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-table.js

1. Add cd-table classes to table element, to avail of styles
2. Add data-content attribute directly to td, hard-code th string as value, for mobile card display.
3. Attempt to hide empty cells
**Intended result:**

AR-173 style Table web component

---

config/block.block.search.yml
config/search_api.index.assessments.yml
config/views.view.assessments.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.theme

1. as Views exposed fulltext field, on Assessments list, with Key Findings field added to the index.
2. Place search in region
3. Theme function for styling

AR-173 CD search

---

html/modules/custom/ocha_assessments/component/package.json
html/modules/custom/ocha_assessments/component/rollup.list.config.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-base.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-list.html
html/modules/custom/ocha_assessments/component/src/ocha-assessments-list.js

https://github.com/UN-OCHA/hrinfo-site/pull/902

Add WC list and pager support

---

config/core.menu.static_menu_link_overrides.yml
config/language.negotiation.yml
config/social_auth.settings.yml
config/social_auth_hid.settings.yml
config/system.site.yml

disable home and my account menu items, set homepage node id, configure hid login

AR-173 configure homepage, login, menu items

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-styles.js

add rule to better wrap anchors so they do not push width of table cells out of viewport

AR-173 Assessment table anchors

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-base.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-styles.js

Wrap filters in form element and add cd- classes, add styles

AR-173 web component filters

---

composer.json
composer.lock

bump base theme version to include grid improvements for homepage, filters component for web component, inline search and better sidebar layout rules
See https://github.com/UN-OCHA/common_design/releases/tag/v2.7.0

AR-173 update base theme version

---

html/modules/custom/ocha_assessments/ocha_assessments.module

@left23 this allows you to select the select2 widget on *Manage form display*

Allow select2 on custom fields

---

config/block.block.authored_on.yml
config/block.block.authored_on_month.yml
config/block.block.levelofrepresentation.yml
config/block.block.map_assessmentdate.yml
config/block.block.map_authored_on.yml
config/block.block.map_status.yml
config/block.block.table_assessmentdate.yml
config/block.block.table_authoredon.yml
config/block.block.table_authoredon_month.yml
config/facets.facet.map_assessment_date.yml
config/facets.facet.table_assessment_date.yml

assessment date for map and table Views list, fix status and level of rep blocks directly in config

AR-180 facet config continued

---

config/field.field.node.assessment.field_assessment_data.yml
config/field.field.node.assessment.field_assessment_questionnaire.yml
config/field.field.node.assessment.field_assessment_report.yml
config/field.field.node.assessment.field_themes.yml

add field descriptions for assessments documents, add file types to match D7

AR-169 assessment form file fields

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-list.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-styles.js

adjust markup for list, adjust styles for list and filters

AR-184 web components continued

---

config/facets.facet.country.yml
config/facets.facet.document_type.yml
config/facets.facet.hpc_document_repository.yml
config/facets.facet.table_status.yml

and attempt to get status to not display if empty on AR Views

AR-180 facet display config for km

---

config/core.entity_form_display.node.assessment.default.yml
config/core.entity_view_display.node.assessment.default.yml
html/themes/custom/cd_seven/css/layout/node-form--assessment.css

1. Correct Contacts field placement - add to field group and adjust CSS
2. Hide Contact display on Assessment node
3. Change Show more button to read Additional information

AR-169 assessment form

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-base.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-list.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-map.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-styles.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-table.js

1. Refine styles for filters, reset button and add pagination styles
2. Adjust pagination markup and add some classes to reset button
3. Move pagination to the bottom, under results

AR-184 web components contined

---

config/core.entity_form_display.node.assessment.default.yml

AR-169 Assessment edit form move countries field

---

html/themes/custom/common_design_subtheme/templates/layout/region--sidebar-first.html.twig

AR-204 close tag in sidebar after conditional open div

---

html/modules/custom/ocha_assessments/component/src/ocha-assessments-map.js

to avoid the apply declaration breaking affecting following declarations

AR-205 Take 2 shuffle order of declarations in map rule

---

composer.json
composer.lock
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-global-header.html.twig

As per AR-208 this should fix the Username variable caching issue, with a base theme update.
Also included are some improvements to the OCHA Services menu. To accommodate the moving of the OCHA Services partial to the footer, I've made the same changes in the sub theme.

AR-208 bump base theme version

---

config/block.block.common_design_subtheme_page_title.yml
config/views.view.knowledge_management.yml

- remove visibility settings from page title block
- add KM Views page title

DOC-42 page title

---

composer.json
composer.lock

Update base theme from using a feature branch to use v.3.0.0 release

CD-270 base theme release

---

html/modules/custom/ocha_docstore_files/src/Plugin/Field/FieldWidget/OchaAssessmentDocumentWidget.php

Fix undefined variable

---

config/core.entity_form_display.local_group.local_group.default.yml

[AR-244] fix config export

---

html/modules/custom/ocha_assessments/component/build/ocha-assessments-map.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-map.js

FYI @lazysoundsystem component needs to be updated on HRInfo as well

Hide map till data

---

PATCHES/views_data_export-fix-number-of-processed-items.patch
html/modules/custom/ocha_assessments/src/Plugin/views/style/PivotFriendlyDataExport.php

Ticket: AR-241
This fixes an issue with the `views_data_export` module not perserving the query conditions (from the facets) between batch runs.

[AR-241] Fix CSV batch export not preserving the selected facets

---

config/external_entities.external_entity_type.local_group.yml

Depends on https://github.com/UN-OCHA/docstore-site/pull/148

Use display name

---

config/block.block.ass_list_localcoordinationgroups.yml
config/block.block.ass_table_localcoordinationgroups.yml
config/facets.facet.ass_list_local_coordination_groups.yml
config/facets.facet.ass_table_local_coordination_groups.yml
html/modules/custom/ocha_assessments/src/Controller/OchaJsonController.php

https://humanitarian.atlassian.net/browse/AR-243
Took a while to get the order right and many many solr-reindexes, but this is working now locally and seems very simple.

[AR-243] add local group filters

---

.gitignore
composer.json
composer.lock
composer.patches.json
config/block.block.ass_list_localcoordinationgroups.yml
config/block.block.ass_table_localcoordinationgroups.yml
config/core.extension.yml
config/external_entities.external_entity_type.local_group.yml
config/facets.facet.ass_list_local_coordination_groups.yml
config/facets.facet.ass_table_local_coordination_groups.yml
docker/Dockerfile
html/modules/custom/ocha_assessments/src/Controller/OchaJsonController.php
html/themes/custom/common_design_subtheme/package-lock.json
symfony.lock

https://humanitarian.atlassian.net/browse/AR-245
https://humanitarian.atlassian.net/browse/AR-243
Ctools and facets updates.

[AR-243] [AR-245] security updates and local group filters

---

config/field.storage.assessment.field_date.yml

https://humanitarian.atlassian.net/browse/AR-239
Update config to remove time from widget.

[AR-239] remove time from assessment date widget

---

config/block.block.ass_list_localcoordinationgroups.yml
config/block.block.ass_table_localcoordinationgroups.yml
config/external_entities.external_entity_type.local_group.yml
config/facets.facet.ass_list_local_coordination_groups.yml
config/facets.facet.ass_table_local_coordination_groups.yml
config/field.field.assessment.assessment.field_local_coordination_groups.yml
config/search_api.index.assessments.yml
config/views.view.assessments.yml
html/modules/custom/ocha_assessments/src/Controller/OchaJsonController.php

https://humanitarian.atlassian.net/browse/AR-247
Renames 'Local coordination groups' and 'Local groups' to 'Clusters'.

[AR-247] rename local groups to clusters

---

composer.lock
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-7493

[OPS-7493] update core to 8.9.16

---

config/external_entities.external_entity_type.location.yml
html/modules/custom/ocha_docstore_files/src/Plugin/ExternalEntities/StorageClient/RestJson.php

Note: This shouldn't be deployed to production before the Docstore is updated with https://github.com/UN-OCHA/docstore-site/pull/159 and its follow-ups.

[AR-240] use display name for locations

---

config/core.entity_form_display.assessment.assessment.default.yml
config/field.storage.assessment.field_date.yml
html/modules/custom/ocha_docstore_files/src/Plugin/Field/FieldWidget/OchaDateRangeDefaultWidget.php

Related to https://github.com/UN-OCHA/docstore-site/pull/171

Save daterange date only

---

config/filter.format.full_html.yml

https://humanitarian.atlassian.net/browse/AR-254
There's an allowed list of html tags in the Full text format. This adds iframes to that list.

[AR-254] allow iframes

---

composer.json
composer.lock
symfony.lock

https://humanitarian.atlassian.net/browse/OPS-7688
Also removes deprecated composer-drupal-optimizations package.

[OPS-7688] update core to 8.9.18

---

composer.lock

https://humanitarian.atlassian.net/browse/OPS-7780

[OPS-7634] update core to 8.9.19

---

composer.json
composer.lock
config/core.extension.yml
config/seckit.settings.yml

https://humanitarian.atlassian.net/browse/OPS-7743

[OPS-7743] add and configure seckit module

---

config/core.entity_form_display.assessment.assessment.default.yml

https://humanitarian.atlassian.net/browse/AR-265
Still an issue locally, but appears to work on staging: https://www.flowdock.com/app/unocha/iasc-secretariat/threads/o_K9WS95rJu0QzStH3WN_z-ShU5

[AR-265] change theme widget to autocomplete

---

config/seckit.settings.yml

Add exceptions found in the logs.

[OPS-7743] add seckit config for more google sites

---

config/seckit.settings.yml

Left out the 'www' in the last commit.

[OPS-7743] add www

---

.github/workflows/docker-build-image.yml

Requires https://github.com/UN-OCHA/assessmentregistry-stack/pull/94 and *also* https://github.com/UN-OCHA/tools-ansible/pull/762

[OPS-7896] Swich to the new build action and to the AWS ECR repository.

---

.github/workflows/docker-build-image.yml
.travis.yml
composer.lock

https://humanitarian.atlassian.net/browse/OPS-7907

[OPS-7907] update core to 9.2.9

---

composer.lock

https://humanitarian.atlassian.net/browse/OPS-7998
Module updates for facets_pretty_paths, geofield, leaflet, search_api, social_auth_hid, token and drush.

[OPS-7998] update contrib modules

---

composer.json
composer.lock

https://humanitarian.atlassian.net/browse/OPS-8028
https://humanitarian.atlassian.net/browse/OPS-8029

[OPS-8028] update core to 9.3.3

---

composer.json
composer.lock

[OPS-8028] make version bump clearer and add composer plugin permissions

---

composer.lock

[OPS-8203] 
update search_api module to 1.23.0
[OPS-8203]: https://humanitarian.atlassian.net/browse/OPS-8203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OPS-8203] update search_api module to "1.23.0"

---

composer.json
composer.lock
composer.patches.json
config/core.extension.yml
config/seckit.settings.yml

fix: add ocha_security module to help seckit

---

config/seckit.settings.yml

chore: restore wwws

---

config/csp.settings.yml

fix: try adding hashes for inline scripts

---

config/csp.settings.yml
config/views.view.export_assessments_metadata.yml

Refs: OPS-8232
and fix a typo.

fix: remove hashes and use unsafe-inline csp config

---

composer.json
composer.lock
composer.patches.json
docker/Dockerfile

chore: Ensure AR does not use redis, so we can sell our RI.

---

PATCHES/csp-log-format.patch
composer.patches.json

fix: simplify log format for csp

---

composer.json
composer.lock
config/csp.settings.yml

fix: remove ocha_security repo, update csp config

---

composer.json
composer.lock
html/modules/custom/ocha_docstore_files/src/Plugin/ExternalEntities/StorageClient/RestJson.php

Refs: AR-286
Fixes issue caused by https://github.com/UN-OCHA/assessmentregistry8-site/pull/407 (and allows updating of the external_entities module.)

fix: update external_entities plugin and module version

---

composer.json
composer.lock
config/core.extension.yml
docker/Dockerfile
docker/memcache.services.yml

Refs: OPS-8319 OPS-8383
This depends on https://github.com/UN-OCHA/tools-ansible/pull/877 - which is already applied on dev.

feat: Add and enable memcache to alleviate RDS load. And Speed!

---

html/modules/custom/ocha_docstore_files/src/Plugin/search_api/processor/StoreEntity.php

Refs: AR-286
To fix https://jenkins.aws.ahconu.org/job/assessments-prod-cron/11653/console

fix: update method call

---

composer.json
composer.lock
config/core.extension.yml
docker/Dockerfile
docker/memcache.services.yml

Includes fix for failing cron job and weekly updates.

Deploy 14-07-2022

---

composer.lock

Deploy 27-07-2022

---

composer.json
composer.lock

Refs: OPS-8550
Core and module updates

Deployment 17-08-2022

---

composer.json
composer.lock

[OPS-8560] monthly module updates

---

.docksal/docksal.env
composer.json
composer.lock
config/core.entity_form_display.km.km.default.yml
config/core.entity_view_display.km.km.default.yml
config/core.entity_view_display.km.km.teaser.yml
config/core.extension.yml
config/field.storage.km.field_description.yml
html/modules/custom/ocha_knowledge_management/ocha_knowledge_management.install
html/themes/custom/common_design_subtheme/templates/content/external-entity--km--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/external-entity--km--teaser.html.twig

Refs: #AR-289
Switch field description to a long HTML field, so users can add links

feat: Use basic html for KM description

---

.docksal/docksal.env
.github/workflows/composer-update.yml
composer.json
composer.lock
config/core.entity_form_display.km.km.default.yml
config/core.entity_view_display.km.km.default.yml
config/core.entity_view_display.km.km.teaser.yml
config/core.extension.yml
config/csp.settings.yml
config/field.field.km.km.field_description.yml
config/field.storage.km.field_description.yml
html/modules/custom/ocha_assessments/component/package-lock.json
html/modules/custom/ocha_knowledge_management/ocha_knowledge_management.install
html/themes/custom/common_design_subtheme/templates/content/external-entity--km--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/external-entity--km--teaser.html.twig

Refs: OPS-8623, AR-289, OPS-8232
Plus CSP config and allow html for description.

[OPS-8623] core security update

---

config/search_api.index.assessments.yml
config/search_api.index.km.yml

Refs: OPS-8623
Changes format of the `specific_languages` config, as exported by `drush cex`.

fix: try again for search_api_solr config

---

composer.patches.json

fix: include patch that's been committed

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/js/cd-hide-export-button.js
html/themes/custom/common_design_subtheme/templates/views/views-view--assessments.html.twig

feat: Hide export button

---

.gitattributes
composer.lock
composer.patches.json
html/.htaccess
html/robots.txt
html/web.config

Refs: OPS-8943
Automatic PR failed due to a patch for search_api_solr which has now been merged.

chore: manual periodic update

---

config/csp.settings.yml

chore: adjust csp again for google domains

---

.dockerignore
docker/Dockerfile

chore: add dockerignore

---

composer.lock

chore: update ocha_integrations module

---

config/views.view.export_km.yml

feat: Export KM meta data

---

.github/workflows/run-tests.yml
html/modules/custom/ocha_docstore_files/src/EventSubscriber/SearchApiSubscriber.php

fix: remove workaround for tests which is breaking cron runs

---

.github/workflows/run-tests.yml

chore: add permissions to tests so dependabot can run okay
