UN-OCHA/assessmentregistry8-site

README.md

Note that I've enabled Travis with the same rules as IASC, but the tests to *not* need to pass for the develop merge at this stage. They *do* for master, though.

[OPS-6303] Add some badges for the pretty.

---

docker/Dockerfile

Fix the use of the GNU iconv library by php7-iconv in the upstream docker image.

[OPS-6486] Bump base image to work around broken inconv()

---

html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/components/cd-table/cd-table.css

override common_design cd-table component with same from sub theme, with adjustments to media queries for better display on tablet size when sidebar is present

AR-173 Responsive tables with facet sidebar

---

html/themes/custom/common_design_subtheme/common_design_subtheme.theme

Issue: https://github.com/UN-OCHA/common_design/issues/87
This adds an attribute to use the cd-dropdown.js focus handling when expanding the search on small screens to ensure the input gets the focus.

Focus search input

---

composer.lock
composer.patches.json

Ticket: OPS-7333
This applies the patch from https://www.drupal.org/project/drupal/issues/2936067 to fix the issue with the css aggregation and the google fonts.
**Note:** Merging https://github.com/UN-OCHA/common_design/pull/179 and https://github.com/UN-OCHA/assessmentregistry8-site/pull/172 should be preferred as it would fix the issue for all the websites using the common design theme as well as the AR site.

[OPS-7333] Apply patch to fix issue with css aggregation and google fonts

---

composer.lock
composer.patches.json

1. Remove patch to fix semi colon issue in google font url breaking css aggregation
2. bump base theme version with alternative fix
Follow up to #172 and #173

OPS-7333 remove patch and bump base theme version to fix CSS aggregation

---

docker/etc/nginx/apps/drupal/drupal.conf

Because, as it turns out, the regex we had did *not* always match URLs
in nginx that it should have matched (and that match fine when testing
the regex). E.g: `01.%20HPC_2021-StepByStep_Guide_0.pdf` tests fine, but
nginx refuses.

[AR-219] Change the way we intercept (and pass) docstore requests.

---

.github/workflows/docker-build-image.yml

@cafuego @attiks Can this be more broad so any feature branches can be deployed to the dev site?
Should the specific `'feature/docstore` be removed?

OPS-7350 Trigger docker builds for all feature/* branches

---

html/modules/custom/ocha_docstore_files/ocha_docstore_files.services.yml
html/modules/custom/ocha_docstore_files/src/EventSubscriber/SearchApiSubscriber.php
html/modules/custom/ocha_docstore_files/src/Plugin/ExternalEntities/StorageClient/RestJson.php
html/modules/custom/ocha_docstore_files/src/Plugin/search_api/datasource/DocstoreEntity.php
html/modules/custom/ocha_docstore_files/src/Plugin/search_api/datasource/DocstoreEntityDeriver.php

Ticket: AR-255
This adds a search API datasource plugin for the docstore external entities extending the `ContentEntity` one in order to remove assumptions regarding languages.
There is also a change to the `RestJson` storage client for the docstore external entities to reduce the number of requests when loading multiple entities.
This speeds up a lot the rebuilding of the tracking and indexing notably.

[AR-255] Search API datasource plugin for external entities

---

config/core.entity_form_display.local_group.local_group.default.yml
config/core.entity_view_display.local_group.local_group.default.yml
config/external_entities.external_entity_type.local_group.yml
config/field.field.local_group.local_group.field_hrinfo_id.yml
config/field.storage.local_group.field_hrinfo_id.yml
config/search_api.index.assessments.yml

Further to https://github.com/UN-OCHA/assessmentregistry8-site/pull/209 , this adds the HRinfo id and exposes the field in the API (I think).
On the docstore, the 'parent' info for local groups is empty (at least in the ones I looked at). I think we need the parent info to give more context to the local group names on the upload form. I'll look at the 'todo's in https://github.com/UN-OCHA/docstore-site/blob/develop/html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php

[AR-224] add local groups with hrinfo id

---

config/search_api.index.assessments.yml

Renames one field to remove ambiguity in the API, and line up with what HRinfo expects.

[AR-224] rename local_groups_id field for api

---

.github/workflows/docker-build-image.yml

* [OPS-7385] Tell GHA that `main` is in fact the production branch.
* [OPS-7385] xmldom is required to build *production* assets, so is not a devDependency.
* [OPS-7385] Fine, then we bake an updated action with `main` built-in as default.
[OPS-7385]: https://humanitarian.atlassian.net/browse/OPS-7385
[OPS-7385]: https://humanitarian.atlassian.net/browse/OPS-7385
[OPS-7385]: https://humanitarian.atlassian.net/browse/OPS-7385

[OPS-7385] Actions branch tweak (#219)

---

html/modules/custom/ocha_assessments/component/build/ocha-assessments-list.js
html/modules/custom/ocha_assessments/component/build/ocha-assessments-map.js
html/modules/custom/ocha_assessments/component/build/ocha-assessments-table.js
html/modules/custom/ocha_assessments/component/src/ocha-assessments-base.js

Ticket: AR-236
This fixes an issue when selecting a filter in the `/list`, `/table` or `/map`.
Note: this was already fixed (another way) in https://github.com/UN-OCHA/assessmentregistry8-site/commit/2e10c28fe2b5defddcbab3a949a020f603d9f285#diff-bdf5be257c607efdfa8e89bd22207f26aa95721b1c7ee043ad18cc10daef3d24 but I just realized that I didn't change the code of the `src` base.js at that time.

[AR-236] Fix active filters

---

docker/etc/nginx/nginx.conf

This whole config can go once we bump images again. See https://github.com/UN-OCHA/docker-images/pull/277

[OPS-7692] The warning suppression line now generates a warning.

---

config/core.entity_form_display.assessment.assessment.default.yml

[AR-283]
updates config to match what's now on prod. https://assessments.hpc.tools/admin/config/development/configuration
We probably need another ticket to remove the field, or to add mapping for it to the docstore, but this is just to ensure the next deployment doesn't un-hide the field.
[AR-283]: https://humanitarian.atlassian.net/browse/AR-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AR-283] hide related content field

---

composer.json
composer.lock
composer.patches.json

[OPS-7998]
When I tried this update to facets before I had an issue with drush not working, but all seems good now. The patch has now been merged: https://www.drupal.org/project/facets/issues/3005040#comment-14361940
[OPS-7998]: https://humanitarian.atlassian.net/browse/OPS-7998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OPS-7998] update facets module to 2.0.2

---

composer.json
composer.lock
composer.patches.json
config/core.extension.yml
config/user_expire.settings.yml

[OPS-7459]
As https://github.com/UN-OCHA/assessmentregistry8-site/pull/360 got complicated by changes to external_entities module, this is the same but only adding and configuring the user_expire module.
[OPS-7459]: https://humanitarian.atlassian.net/browse/OPS-7459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OPS-7459} add and configure user_expire without other changes

---

composer.json
composer.lock
html/.htaccess

Refs: OPS-8392
There's a big change in external_entities - https://www.drupal.org/node/3079012 - which means our use of getFieldMappings() no longer works.
This needs some more work before we can update the module, but it's still in alpha, so there's an argument for waiting a bit longer. That work can be tracked on OPS-8392.
This pins the version of external_entities for the moment.

fix: revert external_entities while still in alpha

---

config/external_entities.external_entity_type.assessment.yml
config/external_entities.external_entity_type.assessment_document.yml
config/external_entities.external_entity_type.assessment_status.yml
config/external_entities.external_entity_type.context.yml
config/external_entities.external_entity_type.country.yml
config/external_entities.external_entity_type.disaster.yml
config/external_entities.external_entity_type.document_type.yml
config/external_entities.external_entity_type.global_cluster.yml
config/external_entities.external_entity_type.hpc_document_repository.yml
config/external_entities.external_entity_type.km.yml
config/external_entities.external_entity_type.life_cycle_step.yml
config/external_entities.external_entity_type.local_group.yml
config/external_entities.external_entity_type.location.yml
config/external_entities.external_entity_type.operation.yml
config/external_entities.external_entity_type.organization.yml
config/external_entities.external_entity_type.population_type.yml
config/external_entities.external_entity_type.theme.yml
config/external_entities.external_entity_type.unit_of_measurement.yml

Refs: AR-286
Was getting an error:
```
  | Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" plugin does not exist. Valid plugin IDs for Drupal\external_entities\FieldMapper\FieldMapperManager are: jsonpath, simple in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /srv/www/html/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
-- | --
```
and discovered the config needed updating.

fix: update config for new mapping schema

---

config/search_api.index.assessments.yml
config/search_api.index.km.yml

Refs: OPS-8623, https://www.drupal.org/project/search_api_solr/issues/3314711
There's an update hook that affects the database only, but not the config, so I think it gets lost on `drush cim`. https://www.drupal.org/project/search_api_solr/issues/3314711

fix: update config for search_api_solr change

---

config/search_api.index.assessments.yml
config/search_api.index.km.yml

Refs: OPS-8623
Reverts to https://github.com/UN-OCHA/assessmentregistry8-site/pull/446/files as https://github.com/UN-OCHA/assessmentregistry8-site/pull/447/files wasn't an improvement.

fix: revert to more simple config setting

---

.travis.yml

Refs: updates
Thinking this is the solution I was looking for in https://github.com/UN-OCHA/assessmentregistry8-site/pull/510

fix: pin composer version till preserve-paths is updated

---

composer.lock

* fix: Bump to the latest release of ocha_integrations to pick up a bugfix that was only in an older release.
* fix: Push to an *actual* new version, not a tag on an old branch.

fix: Bump to the latest release of ocha_integrations to pick up a bugfix.
